<?xml version="1.0"?>
<package format="3">
  <name>image_to_3d</name>
  <version>0.0.0</version>
  <description>image_to_3d is a ROS 2 package for converting camera images into depth and derived 3D representations. It provides nodes for image-to-depth estimation and for converting depth images into PointCloud2 and LaserScan messages.</description>
  <maintainer email="slg@quakemap.com">Sergei Grichine</maintainer>
  <license>Apache 2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>vision_msgs</exec_depend>
  <exec_depend>python3-requests</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>depth_image_proc</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>image_transport_plugins</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
