#
# A configuration file for HuskyLens 2 camera example.
#

image_to_depth_node:
  ros__parameters:
    # Use these when camera is calibrated and camera_info topic is available:
    #input_topic:  camera/image_raw/compressed     
    #input_type:   compressed
    #camera_info_topic: camera/camera_info

    # Use these when camera is not calibrated and camera_info topic is produced by fake_camera_info_node:
    input_topic:  camera_3d/image_raw
    input_type:   raw
    camera_info_topic: camera_3d/camera_info

    output_topic: camera_3d/depth/image_16UC1
    camera_info_output_topic: camera_3d/depth/camera_info  # re-published with same timestamp as depth image

    depth_server: "http://localhost:5001/depth"
    request_timeout: 10.0
    queue_size: 1

image_to_depth_yolo_node:
  ros__parameters:
    # Use these when camera is calibrated and camera_info topic is available:
    #input_topic:  camera/image_raw/compressed     
    #input_type:   compressed
    #camera_info_topic: camera/camera_info

    # Use these when camera is not calibrated and camera_info topic is produced by fake_camera_info_node:
    input_topic:  camera_3d/image_raw
    input_type:   raw
    camera_info_topic: camera_3d/camera_info

    output_topic: camera_3d/depth/image_16UC1
    camera_info_output_topic: camera_3d/depth/camera_info  # re-published with same timestamp as depth image
    detections_topic: camera_3d/detections

    depth_server: "http://localhost:5001/depth"
    inference_server: "http://localhost:5002/detect"
    request_timeout: 10.0
    queue_size: 1

depth_to_laserscan_node:
  ros__parameters:
    target_frame: camera_3d_link
    input_topic:  camera_3d/depth/image_16UC1
    output_topic: camera_3d/scan
    camera_info_topic: camera_3d/depth/camera_info
    num_scan_bins: 160  # good for 640x480 depth image, 4 depth pixels per scan bin
    min_height: -0.1
    max_height: -0.1
    range_min:   0.2
    range_max:  10.0
    scan_time:   0.1

fake_camera_info_node:
  ros__parameters:
    camera_fov: "92.0,76.0" 
    input_topic: camera/image_raw/compressed
    input_type: compressed
    output_topic: camera_3d/image_raw
    output_type: raw
    camera_info_topic: camera_3d/camera_info  # synchronized output with camera image
    frame_id: camera_3d_link_optical

perception_adapter_node:
  ros__parameters:
    person_detected_sound: ""  # aplay is standard on Ubuntu 24, provide full path of a sound file here
    person_detected_text: ""   # what to say, install text-to-speech: sudo apt install flite
    min_confidence: 0.6
    person_cooldown_sec: 3.0   # do not flood output with frequent detection messages
    ticker_interval_sec: 0.1   # Ticker interval (defines rate of publishing all messages)
